
location __PATH__/static/ {
    # Service static files by nginx
    # e.g.: /var/www/$app/static/
    alias __INSTALL_DIR__/static/;
    expires 30d;
}

location __PATH__/ {
    # https://github.com/benoitc/gunicorn/blob/master/examples/nginx.conf

    # this is needed if you have file import via upload enabled
    client_max_body_size 100M;
    proxy_set_header X-Forwarded-Protocol $scheme;

    # Sets `HTTP_YNH_USER` used in django_yunohost_integration

    proxy_read_timeout 30;
    proxy_send_timeout 30;
    proxy_connect_timeout 30;
    proxy_redirect off;

    proxy_pass http://127.0.0.1:__PORT__;

    include proxy_params_with_auth;
}
